server:
  port: 8080

spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://i10a603.p.ssafy.io:3306/petcongdb?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
      username: ssafy
      password: ssafy

logging:
  level:
    web: off
    org.org.hibernate: off
    org.springframework.security.: off

springdoc:
  api-docs:
    enabled: true
    path: /api-docs/json
  swagger-ui:
    enabled: true
    path: /api-docs
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
  cache:
    disabled: true
  packages-to-scan: com.example.ssafy.petcong

allowed-url:
  urls:
    - /members/signin
  patterns:
    - /api-docs/**
    - /swagger-ui/**
    - /websocket/**
