spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://i10a603.p.ssafy.io:3306/petcongdb?serverTimezone=UTC
      username: ssafy
      password: ssafy
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    database-platform: org.hibernate.dialect.MySQLDialect

logging:
  level:
    org.hibernate: off

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    path: /swagger-ui
  cache:
    disabled: true

